swagger: '2.0'
definitions:
   Error:
      description: Objektrepresentation av felmeddelanden.
      type: object
      required:
        - status
        - message
        - path
        - timestamp
      properties:
        status:
          type: integer
          example: 500
          description: Http statuskod
        message:
          type: string
          example: 'Tekniskt fel, försök senare'
          description: Innehåller ett felmeddelande tänkt att presenteras för slutanvändare
        exception:
          type: string
          example: java.lang.NullPointerException
          description: Innehåller ett felmeddelande tänkt för tekniker vid felsökning
        path:
          type: string
          example: /lamning
          description: Anger den resourcepath där felet uppstod
        timestamp:
          type: string
          format: dateTime
          description: Anger tidpunkten när felet inträffade.
            Tidpunkt anges enligt defined by full-date - RFC3339.
            Se RFC3339 (Internet Date/Time Format) http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14
            Syntax; <date-fullyear>-<date-month>-<date-mday> <time-hour>:<time-minute>:<time-second>
          example: '2017-10-30 08:00:18'
        code:
          description: "Kod som beskriver vilket fel som inträffat:
            <ul>
              <li>INVALID_OR_MISSING_VALUE: Ett värde var ogiltigt, felaktigt formatterat eller saknades, till exempel obligatoriskt fält saknades</li>
              <li>METADATA_VALIDATION_FAILED: Det skedde ett fel då metadata skulle valideras, till exempel inaktivt metadata-värde angivet</li>
              <li>INCORRECT_INPUT_FORMAT: Indata-formatet var felaktigt, felet fås då till exempel felaktig json-syntax angivits</li>
              <li>DATABASE_CONSTRAINT_ERROR: Fel vid skrivning till databas</li>
              <li>GENERIC_ERROR_OCCURRED: Okänt fel intäffade</li>
            </ul>"
          $ref: '#/definitions/ErrorCodes'
   ErrorCodes:
      type: string
      enum:
        - INVALID_OR_MISSING_VALUE
        - METADATA_VALIDATION_FAILED
        - INCORRECT_INPUT_FORMAT
        - DATABASE_CONSTRAINT_ERROR
        - GENERIC_ERROR_OCCURRED
